#!/usr/bin/env php
<?php
declare(strict_types = 1);

$started = false;
$autoloads = [__DIR__ . '/vendor/autoload.php', __DIR__ . '/../../autoload.php'];

foreach ($autoloads as $autoload) {
    if (file_exists($autoload)) {
        require $autoload;
        $started = true;
        break;
    }
}
if (!$started)
    die('Please, run composer install.');

require_once __DIR__.'/./source/globals.php';

use Symfony\Component\Console\Application;
$application = new Application(APP_NAME);

$application->add(new \Insphptor\Program\Commands\RunCommand);
$application->add(new \Insphptor\Program\Commands\ExportCommand);
$application->add(new \Insphptor\Program\Commands\InitCommand);
$application->add(new \Insphptor\Program\Commands\StartCommand);
$application->add(new \Insphptor\Program\Commands\CleanCommand);

\Insphptor\Program\Config\Config::instance();

$application->run();