#!/usr/bin/env php
<?php
declare(strict_types = 1);

require_once __DIR__.'/./vendor/autoload.php';

require_once __DIR__.'/./source/globals.php';

use Symfony\Component\Console\Application;
$application = new Application(APP_NAME);

$application->add(new \Insphptor\Program\Commands\RunCommand);
$application->add(new \Insphptor\Program\Commands\ExportCommand);
$application->add(new \Insphptor\Program\Commands\InitCommand);

$application->run();