#!/usr/bin/env php
<?php
declare(strict_types = 1);

use Webmozart\Console\ConsoleApplication;
use Insphptor\Program\Application;

require_once __DIR__.'/./vendor/autoload.php';

require_once __DIR__.'/./source/globals.php';

$cli = new ConsoleApplication(new Application());
$cli->run();